# Generated by Django 5.1.3 on 2024-11-28 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "permissions": [
                    (
                        "send_private_email",
                        "Can send private email to user by the button",
                    )
                ]
            },
        ),
    ]
