# Generated by Django 5.1.3 on 2024-11-30 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customer_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
